apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stakit.fullname" . }}-frontend
  namespace: {{ .Values.namespace | default "default" }}  
  labels:
    {{- include "stakit.labels" . | nindent 4 }}
spec:
  {{- if not .Values.frontend.autoscaling.enabled }}
  replicas: {{ .Values.frontend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "stakit.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.frontend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "stakit.frontend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: false
      volumes:
        - emptyDir: {}
          name: etc
        - emptyDir: {}
          name: init
        - emptyDir: {}
          name: nginx-cache
        - emptyDir: {}
          name: var
        - emptyDir: {}
          name: tmp
      securityContext:
        {{- toYaml .Values.frontend.podSecurityContext | nindent 8 }}
      initContainers:
        - name: {{ .Chart.Name }}-frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          volumeMounts:
            - mountPath: /temp/etc/nginx
              name: etc
            - mountPath: /temp/docker-entrypoint.d
              name: init
            - mountPath: /temp/var/cache/nginx
              name: nginx-cache
            - mountPath: /temp/var/run
              name: var
          env: {{ if (not .Values.frontend.deployment.env) }}[]{{ end }}
            {{- range $key, $value := .Values.frontend.deployment.env }}
            - name: {{ $key }}
            {{- if (not $value.type) }}
              value: {{ $value.value | quote }}
            {{- else if eq $value.type "fieldPath" }}
              valueFrom:
                fieldRef:
                  fieldPath: {{ $value.value }}
            {{- else if eq $value.type "secretKeyRef" }}
              valueFrom:
                secretKeyRef:
                  key: {{ $value.key }}
                  name: {{ $value.name }}
            {{- end }}
            {{- end }}  
      containers:
        - name: {{ .Chart.Name }}-frontend
          securityContext:
            {{- toYaml .Values.frontend.securityContext | nindent 12 }}
          image: {{ .Values.frontend.nginxImageOverride | default "nginxinc/nginx-unprivileged:alpine3.17" }}
          imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }}  
          volumeMounts:
            - mountPath: /etc/nginx
              name: etc
            - mountPath: /docker-entrypoint.d
              name: init
            - mountPath: /var/cache/nginx
              name: nginx-cache
            - mountPath: /var/run
              name: var
            - mountPath: /tmp
              name: tmp
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}        
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
