apiVersion: v1
kind: Service
metadata:
  name: {{ include "stakit.fullname" . }}-frontend
  namespace: {{ .Values.namespace | default "default" }}  
  labels:
    {{- include "stakit.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "stakit.frontend.selectorLabels" . | nindent 4 }}
