# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

    # if below step is skipped this build is a tag build. Can be used for skipping other steps.
      - name: Is Tag Build
        id: tag
        if:  ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}

      - name: Is Trunk Build
        id: trunk
        if:  ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: echo ::set-output name=VERSION::'0.0.0'

      - name: Build and test helm chart
        run: ./build/build-helm.sh stakit ${{ steps.tag.outputs.VERSION }} ${{ steps.trunk.outputs.VERSION }}

      - name: Update documentation
        if: ${{ steps.trunk.conclusion != 'skipped' }}
        run: ./build/helm-docs.sh

      - name: Push tagged helm chart to repo
        if: ${{ steps.tag.conclusion != 'skipped' }}
        run: ./build/push-repo.sh ${{ secrets.KIT_GITHUB_ACCESS }}
